global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'graylog'
    scrape_interval: 15s
    metrics_path: '/api/plugins/org.graylog.plugins.metrics.prometheus/metrics'
    static_configs:
      - targets: ['graylog']
    basic_auth:
      username: admin
      password: admin

  - job_name: 'snmp'
    scrape_interval: 120s
    scrape_timeout: 120s
    static_configs:
     - targets:
       - 192.168.10.4
       - 192.168.10.21
       - 192.168.10.23
       - 192.168.10.249
       - 192.168.10.250
       - 192.168.10.251
       - 192.168.10.252
       - 192.168.10.254
       - 192.168.10.246 
    metrics_path: /metrics
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.10.121:9116 # The SNMP exporter's real hostname:port.
      - source_labels: [storvix]
        target_label: _param_community
      - source_labels: [mibs]
        target_label: _param_module

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
     - targets: ['alertmanager:9093']
